apiVersion: v1
kind: Service
metadata:
  name: myproj-service
spec:
  type: NodePort
  ports:
    - targetPort: 8001
      port: 80
      nodePort: 30008
  selector:
    app: myproj
    type: front-end

# curl http://173.193.124.243:30008/ConfigData/dev (where Public IP of Node is 173.193.124.243)
#use "labels" from pod defs in the selector section